include:
  - component: $CI_SERVER_FQDN/wg-electronictransportdocuments/ecmr/ecmr_ci/docker-build@main
  - component: $CI_SERVER_FQDN/wg-electronictransportdocuments/ecmr/ecmr_ci/docker-build@main
    inputs:
      name_postfix: -archive
      stage: archive
      image_name: "$CI_COMMIT_REF_SLUG"
      image_tag: "latest"
  - template: Code-Quality.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml

variables:
  PROJECT_PREFIX: "/ecmr-frontend"
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: ""
  # Set Docker Host to GitLab Registry
  # DOCKER_HOST: "tcp://0.0.0.0:2375"
  # See Code Quality Image
  # DOCKER_DRIVER: overlay2
  # DOCKER_TLS_VERIFY: 1
  # DOCKER_SOCKET_PATH: /var/run/docker.sock
  # DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  # DOCKER_BUILDKIT: "1"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Extend the default stages with the archive stage intended to push artifacts to the nexus
# Bear in mind that the K8s cluster may pick up docker images from the registry by itself if
# a particular imagestream is configured as such
stages:
  - build
  - test
  - quality
  - archive
  - deploy

node-build-angular-frontend:
  trigger:
    include:
      - local: angular-frontend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
      - angular-frontend/**/*

code_quality:
  stage: quality
  tags:
    - ecmr
  variables:
    CODECLIMATE_REGISTRY_USERNAME: $CI_REGISTRY_USER
    CODECLIMATE_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
