services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

include:
  - project: 'AAD/Shared/pipeline_templates'
    ref: 'main'
    file: 'deploy.yml'
  - project: 'AAD/Shared/pipeline_templates'
    ref: 'main'
    file: 'docker_build_publish.yml'
  - project: 'AAD/Shared/pipeline_templates'
    ref: 'main'
    file: 'build_npm.yml'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "logout_test"
    - if: $CI_COMMIT_BRANCH =~ /^release/
    - if: $CI_COMMIT_BRANCH =~ /^hotfix/

stages:
  - docker_build_publish
  - release
  - deploy

set_variables:
  image: rhsas0002rg0008cr0001.azurecr.io/prod/rhenus_base_deploy:ubuntu-2204
  stage: docker_build_publish
  script:
    - VERSION=$(echo "$CI_COMMIT_BRANCH" | awk -F'/' '{print $NF}')
    - echo "VERSION=$VERSION" >> variables.env
    - echo "GIT_TAG=v$VERSION" >> variables.env
  artifacts:
    when: always
    reports:
      dotenv: variables.env
    expire_in: 1 hour

docker_build_test:
  stage: docker_build_publish
  extends: .docker_build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

docker_build_publish_test:
  stage: docker_build_publish
  extends: .docker_build_publish
  variables:
    CONTAINER_REGISTRY: '$AZURE_CONTAINER_REGISTRY'
    CONTAINER_REGISTRY_USER: '$AZURE_CONTAINER_REGISTRY_USER_TEST'
    CONTAINER_REGISTRY_PW: '$AZURE_CONTAINER_REGISTRY_PW_TEST'
    IMAGE_NAME: '$AZURE_CONTAINER_REGISTRY/test/ecmr-frontend'
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

docker_build_publish_test_logout:
  stage: docker_build_publish
  extends: .docker_build_publish
  variables:
    CONTAINER_REGISTRY: '$AZURE_CONTAINER_REGISTRY'
    CONTAINER_REGISTRY_USER: '$AZURE_CONTAINER_REGISTRY_USER_TEST'
    CONTAINER_REGISTRY_PW: '$AZURE_CONTAINER_REGISTRY_PW_TEST'
    IMAGE_NAME: '$AZURE_CONTAINER_REGISTRY/test/ecmr-frontend'
  rules:
    - if: $CI_COMMIT_BRANCH == "logout_test"

docker_build_publish_qa:
  stage: docker_build_publish
  extends: .docker_build_publish
  variables:
    CONTAINER_REGISTRY: '$AZURE_CONTAINER_REGISTRY'
    CONTAINER_REGISTRY_USER: '$AZURE_CONTAINER_REGISTRY_USER_TEST'
    CONTAINER_REGISTRY_PW: '$AZURE_CONTAINER_REGISTRY_PW_TEST'
    IMAGE_NAME: '$AZURE_CONTAINER_REGISTRY/qa/ecmr-frontend'
  when: manual
  needs:
    - set_variables
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
    - if: $CI_COMMIT_BRANCH =~ /^hotfix/

docker_build_publish_prod:
  stage: docker_build_publish
  extends: .docker_build_publish
  variables:
    CONTAINER_REGISTRY: '$AZURE_CONTAINER_REGISTRY'
    CONTAINER_REGISTRY_USER: '$AZURE_CONTAINER_REGISTRY_USER_PROD'
    CONTAINER_REGISTRY_PW: '$AZURE_CONTAINER_REGISTRY_PW_PROD'
    IMAGE_NAME: '$AZURE_CONTAINER_REGISTRY/prod/ecmr-frontend'
    IMAGE_TAG: '$VERSION'
  when: manual
  needs: 
    - set_variables
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
    - if: $CI_COMMIT_BRANCH =~ /^hotfix/

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  environment: production
  needs:
    - set_variables
    - docker_build_publish_prod
  when: on_success
  script:
    - echo Creating Release "$GIT_TAG"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
    - if: $CI_COMMIT_BRANCH =~ /^hotfix/
  release:
    name: 'Release $GIT_TAG'
    tag_name: $GIT_TAG
    description: 'Created by Pipeline'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'Docker Image'
          url: 'https://$IMAGE'

deploy-test:
  variables:
    IMAGE: '$IMAGE' # needs to be overwritten, Image Tag der angepasst werden soll, inklusive Repository URL
    DEPLOYMENT_FILE: 'config/aad-dev/ecmr-test/frontend/2-deployment.yaml' # needs to be overwritten, deployment Datei die verändert werden soll
    CONTAINER_NAME: 'ecmr-frontend' # needs to be overwritten, Name des Containers im Deploymentfile
  stage: deploy
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy-test-logout:
  variables:
    IMAGE: '$IMAGE' # needs to be overwritten, Image Tag der angepasst werden soll, inklusive Repository URL
    DEPLOYMENT_FILE: 'config/aad-dev/ecmr-test/frontend/2-deployment.yaml' # needs to be overwritten, deployment Datei die verändert werden soll
    CONTAINER_NAME: 'ecmr-frontend' # needs to be overwritten, Name des Containers im Deploymentfile
  stage: deploy
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "logout_test"

deploy-qa:
  variables:
    IMAGE: '$IMAGE' # needs to be overwritten, Image Tag der angepasst werden soll, inklusive Repository URL
    DEPLOYMENT_FILE: 'config/aad-dev/ecmr-qa/frontend/2-deployment.yaml' # needs to be overwritten, deployment Datei die verändert werden soll
    CONTAINER_NAME: 'ecmr-frontend' # needs to be overwritten, Name des Containers im Deploymentfile
  stage: deploy
  extends: .deploy
  when: on_success
  needs:
    - docker_build_publish_qa
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
    - if: $CI_COMMIT_BRANCH =~ /^hotfix/

deploy-prod:
  variables:
    IMAGE: '$IMAGE' # needs to be overwritten, Image Tag der angepasst werden soll, inklusive Repository URL
    DEPLOYMENT_FILE: 'config/aad-prod/ecmr/frontend/2-deployment.yaml' # needs to be overwritten, deployment Datei die verändert werden soll
    CONTAINER_NAME: 'ecmr-frontend' # needs to be overwritten, Name des Containers im Deploymentfile
  stage: deploy
  extends: .deploy
  when: on_success
  needs:
    - docker_build_publish_prod
    - release
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
    - if: $CI_COMMIT_BRANCH =~ /^hotfix/
