
variables:
  PROJECT_PREFIX: "/ecmr-frontend"
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: ""
  # Set Docker Host to GitLab Registry
  # DOCKER_HOST: "tcp://0.0.0.0:2375"
  # See Code Quality Image
  # DOCKER_DRIVER: overlay2
  # DOCKER_TLS_VERIFY: 1
  # DOCKER_SOCKET_PATH: /var/run/docker.sock
  # DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  # DOCKER_BUILDKIT: "1"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Extend the default stages with the archive stage intended to push artifacts to the nexus
# Bear in mind that the K8s cluster may pick up docker images from the registry by itself if
# a particular imagestream is configured as such
stages:
  - build
  - test
  - archive
  - deploy

node-build-angular-frontend:
  trigger:
    include:
      - local: angular-frontend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
      - angular-frontend/**/*

docker-build-angular-frontend:
  tags:
    - ecmr
  variables:
    IMAGE_TAG: "latest"
    IMAGE_NAME: $CI_COMMIT_REF_SLUG
  stage: archive
  cache: {}
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  before_script:
  - rm -rf ~/.docker/manifests || true
  script:
  - echo "CI_REGISTRY=$CI_REGISTRY"
  - echo "DOCKER_HOST=$DOCKER_HOST"
  - echo "CI_PROJECT_DIR=${CI_PROJECT_DIR}"
  - echo "$IMAGE_TAG={$IMAGE_TAG}"
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$IMAGE_NAME:$IMAGE_TAG"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - angular-frontend/**/*
