include:
  - local: '.gitlab/ci_cd_templates/Npm-Angular.gitlab-ci.yml'

# Extend the default stages with the archive stage intended to push artifacts to the nexus
# Bear in mind that the K8s cluster may pick up docker images from the registry by itself if
# a particular imagestream is configured as such
stages:
  - build
  - test
  - quality
  - archive

build:
  stage: build
  tags:
    - active
  extends: .npm-angular-build
  variables:
    PROJECT_DIR: "angular-frontend/"

test:
  stage: test
  tags:
    - active
  extends: .npm-angular-test
  needs:
    - job: build
      artifacts: true
  artifacts:
    reports:
      junit: $CI_PROJECT_DIR/angular-frontend/coverage/tests/junit-test-results.xml
      coverage_report:
        coverage_format: cobertura
        path: $CI_PROJECT_DIR/angular-frontend/coverage/angular-frontend/cobertura-coverage.xml
    paths:
      - $CI_PROJECT_DIR/angular-frontend/coverage/tests/junit-test-results.xml
      - $CI_PROJECT_DIR/angular-frontend/coverage/angular-frontend/cobertura-coverage.xml
  variables:
    PROJECT_DIR: "angular-frontend/"

lint:
  stage: quality
  tags:
    - active
  needs:
    - job: build
      artifacts: true
  artifacts:
    reports:
      codequality: $CI_PROJECT_DIR/${PROJECT_DIR}gl-code-quality-report.json
  extends: .npm-angular-lint
  variables:
    PROJECT_DIR: "angular-frontend/"

third-party-license-check:
  stage: test
  tags:
    - active
  extends: .npm-angular-third-party-license-check
  variables:
    PROJECT_DIR: "angular-frontend/"

#artifacts-archive:
#  stage: archive
#  extends: .npm-angular-archive
#  variables:
#    PROJECT_DIR: "angular-frontend/"
#    PACKAGE_JSON_PATH: "angular-frontend/package.json"
