server {

  listen 8080;
  sendfile on;

  default_type application/octet-stream;

  gzip on;
  gzip_http_version 1.1;
  gzip_disable      "MSIE [1-6]\.";
  gzip_min_length   1100;
  gzip_vary         on;
  gzip_proxied      expired no-cache no-store private auth;
  gzip_types        text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_comp_level   9;

  root /usr/share/nginx/html;

  location /api/ {
    proxy_pass http://ecmr-backend:8081; # A backend konténer neve és belső portja
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Content-Security-Policy "connect-src 'self' http://92.82.187.143:8090 http://92.82.187.143:8091 http://92.82.187.143:8092 *.microsoftonline.com; font-src 'self' *.googleapis.com *.gstatic.com *.jsdelivr.net; frame-src 'self'; script-src 'self' 'unsafe-inline' *.cloudflareinsights.com 'unsafe-eval'; style-src 'self' 'unsafe-inline' *.googleapis.com; frame-ancestors 'self' https://*.cargotrack.ro; img-src 'self' data:; manifest-src 'self'; media-src 'self'; object-src 'self'; worker-src 'self';" always;
  }

}